FROM python:3.9-slim

WORKDIR /app

# Install the necessary dependencies
RUN pip install streamlit pyhive pandas plotly thrift thrift-sasl

# Copy the ecommerce data into the container
COPY ../data/data.csv /app/

# Copy the Streamlit app into the container
COPY app*.py /app/

EXPOSE 8501

# Run the Streamlit app
CMD ["streamlit", "run", "app.py"]